operator_dict = {
   "ram": {
      "name": "Ram",
      "safename": "ram",
      "realname": "Bo-Ram Choi",
      "birthplace": "Busan, South Korea",
      "age": 37,
      "date_of_birth": "April 25",
      "season_introduced": "Y8S4",
      "health": 3,
      "speed": 1,
      "unit": "Redhammer",
      "country_code": "KR",
      "roles": ["Breach"],
      "side": "attacker",
      "icon_url": "https://i.imgur.com/NokDK0I.png",
   },
   "fenrir": {
      "name": "Fenrir",
      "safename": "fenrir",
      "realname": "Emil Svensson",
      "birthplace": "Uppsala, Sweden",
      "age": 34,
      "date_of_birth": "December 3rd",
      "season_introduced": "Y8S2",
      "health": 2,
      "speed": 2,
      "unit": "Redhammer",
      "country_code": "SE",
      "roles": ["Trapper"],
      "side": "defender",
      "icon_url": "https://i.imgur.com/6T16oPJ.png",
   },
   "brava": {
      "name": "Brava",
      "safename": "brava",
      "realname": "Nayara Cardoso",
      "birthplace": "Curitiba, Brazil",
      "age": 40,
      "date_of_birth": "January 10th",
      "season_introduced": "Y8S1",
      "health": 1,
      "speed": 3,
      "unit": "Viperstrike",
      "country_code": "BR",
      "roles": ["Intel", "Anti Gadget"],
      "side": "attacker",
      "icon_url": "https://i.imgur.com/1Se82ke.png",
   },
   "solis": {
      "name": "Solis",
      "safename": "solis",
      "realname": "Ana Valentina Díaz",
      "birthplace": "Zipaquirá, Colombia",
      "age": 37,
      "date_of_birth": "September 18th",
      "season_introduced": "Y7S4",
      "health": 2,
      "speed": 2,
      "unit": "AFEAU",
      "country_code": "CO",
      "roles": ["Intel Gatherer"],
      "side": "defender",
      "icon_url": "https://i.imgur.com/PgtffOh.png",
   },
   "grim": {
      "name": "Grim",
      "safename": "grim",
      "realname": "Charlie Tho Keng Boon",
      "birthplace": "Jurong, Singapore",
      "age": 39,
      "date_of_birth": "April 5th",
      "season_introduced": "Y7S3",
      "health": 1,
      "speed": 3,
      "unit": "Nighthaven",
      "country_code": "",
      "roles": ["Intel Gatherer", "Area Denial"],
      "side": "attacker",
      "icon_url": "https://i.imgur.com/dV5ilwv.png",
   },
   "sens": {
      "name": "Sens",
      "safename": "sens",
      "realname": "Néon Ngoma Mutombo",
      "birthplace": "Brussels, Belgium",
      "age": 30,
      "date_of_birth": "March 3rd",
      "season_introduced": "Y7S2",
      "health": 1,
      "speed": 3,
      "unit": "SFG",
      "country_code": "BE",
      "roles": ["Covering Fire", "Area Denial", "Crowd Control"],
      "side": "attacker",
      "icon_url": "https://i.imgur.com/kwfMIVz.png",
   },
   "azami": {
      "name": "Azami",
      "safename": "azami",
      "realname": "Kana Fujiwara",
      "birthplace": "Kyoto, Japan",
      "age": 28,
      "date_of_birth": "September 6th",
      "season_introduced": "Y7S1",
      "health": 2,
      "speed": 2,
      "unit": "UNAFFILIATED",
      "country_code": "JP",
      "roles": ["Area Denial"],
      "side": "defender",
      "icon_url": "https://i.imgur.com/QnqklyT.png",
   },
   "thorn": {
      "name": "Thorn",
      "safename": "thorn",
      "realname": "Brianna Skehan",
      "birthplace": "County Kildare, Ireland",
      "age": 28,
      "date_of_birth": "June 18th",
      "season_introduced": "Y6S4",
      "health": 2,
      "speed": 2,
      "unit": "GARDA SÍOCHÁNA",
      "country_code": "IE",
      "roles": ["Anchor", "Secure"],
      "side": "defender",
      "icon_url": "https://i.imgur.com/w5DB6xs.png",
   },
   "osa": {
      "name": "Osa",
      "safename": "osa",
      "realname": "Anja Katarina Janković",
      "birthplace": "Split, Croatia",
      "age": 27,
      "date_of_birth": "April 29th",
      "season_introduced": "Y6S3",
      "health": 3,
      "speed": 1,
      "unit": "NIGHTHAVEN",
      "country_code": "HR",
      "roles": ["Intel Gatherer", "Area Denial", "Anti Roam"],
      "side": "attacker",
      "icon_url": "https://i.imgur.com/odZHbem.png",
   },
   "thunderbird": {
      "name": "Thunderbird",
      "safename": "thunderbird",
      "realname": "Mina Sky",
      "birthplace": "Nakoda Territories",
      "age": 36,
      "date_of_birth": "April 1st",
      "season_introduced": "Y6S2",
      "health": 2,
      "speed": 2,
      "unit": "UNAFFILIATED",
      "country_code": "",
      "roles": ["Secure", "Roam", "Buff"],
      "side": "defender",
      "icon_url": "https://i.imgur.com/21vn9y7.png",
   },
   "flores": {
      "name": "Flores",
      "safename": "flores",
      "realname": "Santiago Miguel Lucero",
      "birthplace": "Buenos Aires, Argentina",
      "age": 38,
      "date_of_birth": "April 1st",
      "season_introduced": "Y6S1",
      "health": 2,
      "speed": 2,
      "unit": "UNAFFILIATED",
      "country_code": "AR",
      "roles": ["Soft Breach", "Disable", "Area Denial", "Back Line"],
      "side": "attacker",
      "icon_url": "https://i.imgur.com/1wBdB2q.png",
   },
   "aruni": {
      "name": "Aruni",
      "safename": "aruni",
      "realname": "Apha Tawanroong",
      "birthplace": "Ta Phraya District, Thailand",
      "age": 42,
      "date_of_birth": "August 9th",
      "season_introduced": "Y5S4",
      "health": 3,
      "speed": 1,
      "unit": "NIGHTHAVEN",
      "country_code": "TH",
      "roles": ["Secure", "Intel Gatherer", "Anchor"],
      "side": "defender",
      "icon_url": "https://i.imgur.com/PhCM38D.png",
   },
   "zero": {
      "name": "Zero",
      "safename": "zero",
      "realname": "Samuel Leo Fisher",
      "birthplace": "Baltimore, Maryland",
      "age": 63,
      "date_of_birth": "August 8th",
      "season_introduced": "Y5S3",
      "health": 1,
      "speed": 3,
      "unit": "ROS",
      "country_code": "US",
      "roles": ["Intel Denier", "Intel Gatherer"],
      "side": "attacker",
      "icon_url": "https://i.imgur.com/87LCqv1.png",
   },
   "ace": {
      "name": "Ace",
      "safename": "ace",
      "realname": "Håvard Haugland",
      "birthplace": "Lærdalsøyri, Norway",
      "age": 33,
      "date_of_birth": "March 15th",
      "season_introduced": "Y5S2",
      "health": 2,
      "speed": 2,
      "unit": "NIGHTHAVEN",
      "country_code": "NO",
      "roles": ["Front Line", "Hard Breach"],
      "side": "attacker",
      "icon_url": "https://i.imgur.com/GwWGSuu.png",
   },
   "melusi": {
      "name": "Melusi",
      "safename": "melusi",
      "realname": "Thandiwe Ndlovu",
      "birthplace": "Louwsburg, South Africa",
      "age": 32,
      "date_of_birth": "June 16th",
      "season_introduced": "Y5S2",
      "health": 3,
      "speed": 1,
      "unit": "ITF",
      "country_code": "SA",
      "roles": ["Crowd Control", "Intel Gatherer", "Secure"],
      "side": "defender",
      "icon_url": "https://i.imgur.com/7BNXQnr.png",
   },
   "oryx": {
      "name": "Oryx",
      "safename": "oryx",
      "realname": "Saif Al Hadid",
      "birthplace": "Azraq, Jordan",
      "age": 45,
      "date_of_birth": "July 3rd",
      "season_introduced": "Y5S1",
      "health": 2,
      "speed": 2,
      "unit": "UNAFFILIATED",
      "country_code": "JO",
      "roles": ["Roam", "Soft Breach"],
      "side": "defender",
      "icon_url": "https://i.imgur.com/BdJnmYf.png",
   },
   "iana": {
      "name": "Iana",
      "safename": "iana",
      "realname": "Nienke Meijer",
      "birthplace": "Katwijk, the Netherlands",
      "age": 35,
      "date_of_birth": "August 27th",
      "season_introduced": "Y5S1",
      "health": 2,
      "speed": 2,
      "unit": "REU",
      "country_code": "NL",
      "roles": ["Intel Denier", "Intel Gatherer"],
      "side": "attacker",
      "icon_url": "https://i.imgur.com/bk77LOt.png",
   },
   "wamai": {
      "name": "Wamai",
      "safename": "wamai",
      "realname": "Ngũgĩ Muchoki Furaha",
      "birthplace": "Lamu, Kenya",
      "age": 28,
      "date_of_birth": "June 1st",
      "season_introduced": "Y4S4",
      "health": 2,
      "speed": 2,
      "unit": "NIGHTHAVEN",
      "country_code": "KE",
      "roles": ["Anchor", "Secure"],
      "side": "defender",
      "icon_url": "https://i.imgur.com/bFRCKTJ.png",
   },
   "kali": {
      "name": "Kali",
      "safename": "kali",
      "realname": "Jaimini Kalimohan Shah",
      "birthplace": "Amreli, India",
      "age": 34,
      "date_of_birth": "August 21st",
      "season_introduced": "Y4S4",
      "health": 2,
      "speed": 2,
      "unit": "NIGHTHAVEN",
      "country_code": "IN",
      "roles": ["Back Line", "Covering Fire", "Disable"],
      "side": "attacker",
      "icon_url": "https://i.imgur.com/sQGypuE.png",
   },
   "amaru": {
      "name": "Amaru",
      "safename": "amaru",
      "realname": "Azucena Rocío Quispe",
      "birthplace": "Cojata, Peru",
      "age": 48,
      "date_of_birth": "May 6th",
      "season_introduced": "Y4S3",
      "health": 2,
      "speed": 2,
      "unit": "APCA",
      "country_code": "PE",
      "roles": ["Flank", "Front Line"],
      "side": "attacker",
      "icon_url": "https://i.imgur.com/m5u47Mw.png",
   },
   "goyo": {
      "name": "Goyo",
      "safename": "goyo",
      "realname": "César Ruiz Hernández",
      "birthplace": "Culiacán Rosales, Mexico",
      "age": 31,
      "date_of_birth": "June 20th",
      "season_introduced": "Y4S3",
      "health": 2,
      "speed": 2,
      "unit": "FES",
      "country_code": "MX",
      "roles": ["Area Denial", "Secure"],
      "side": "defender",
      "icon_url": "https://i.imgur.com/tYPrtCH.png",
   },
   "nokk": {
      "name": "Nøkk",
      "safename": "nokk",
      "realname": "REDACTED",
      "birthplace": "REDACTED",
      "age": 00,
      "date_of_birth": "REDACTED",
      "season_introduced": "Y4S2",
      "health": 2,
      "speed": 2,
      "unit": "JAEGER CORPS",
      "country_code": "DK",
      "roles": ["Flank", "Intel Denier"],
      "side": "attacker",
      "icon_url": "https://i.imgur.com/oleTyHs.png",
   },
   "warden": {
      "name": "Warden",
      "safename": "warden",
      "realname": "Collinn McKinley",
      "birthplace": "Louisville, Kentucky",
      "age": 48,
      "date_of_birth": "March 18th",
      "season_introduced": "Y4S2",
      "health": 2,
      "speed": 2,
      "unit": "SECRET SERVICE",
      "country_code": "US",
      "roles": ["Anchor", "Intel Denier"],
      "side": "defender",
      "icon_url": "https://i.imgur.com/HqTIR7x.png",
   },
   "mozzie": {
      "name": "Mozzie",
      "safename": "mozzie",
      "realname": "Max Goose",
      "birthplace": "Portland, Australia",
      "age": 35,
      "date_of_birth": "February 15th",
      "season_introduced": "Y4S1",
      "health": 2,
      "speed": 2,
      "unit": "SASR",
      "country_code": "AN",
      "roles": ["Intel Denier", "Intel Gatherer", "Secure"],
      "side": "defender",
      "icon_url": "https://i.imgur.com/yrFXGCn.png",
   },
   "gridlock": {
      "name": "Gridlock",
      "safename": "gridlock",
      "realname": "Tori Tallyo Fairous",
      "birthplace": "Longreach, Central Queensland, Australia",
      "age": 36,
      "date_of_birth": "August 5th",
      "season_introduced": "Y4S1",
      "health": 3,
      "speed": 1,
      "unit": "SASR",
      "country_code": "AN",
      "roles": ["Anti Roam", "Area Denial", "Crowd Control"],
      "side": "attacker",
      "icon_url": "https://i.imgur.com/WHkIm3H.png",
   },
   "nomad": {
      "name": "Nomad",
      "safename": "nomad",
      "realname": "Sanaa El Maktoub",
      "birthplace": "Marrakesh, Morocco",
      "age": 39,
      "date_of_birth": "July 27th",
      "season_introduced": "Y3S4",
      "health": 2,
      "speed": 2,
      "unit": "GIGR",
      "country_code": "MA",
      "roles": ["Anti Roam", "Crowd Control", "Trap"],
      "side": "attacker",
      "icon_url": "https://i.imgur.com/2I6OWIz.png",
   },
   "kaid": {
      "name": "Kaid",
      "safename": "kaid",
      "realname": "Jalal El Fassi",
      "birthplace": "Aroumd, Morocco",
      "age": 58,
      "date_of_birth": "June 26th",
      "season_introduced": "Y3S4",
      "health": 3,
      "speed": 1,
      "unit": "GIGR",
      "country_code": "MA",
      "roles": ["Anchor", "Anti Hard Breach", "Secure"],
      "side": "defender",
      "icon_url": "https://i.imgur.com/Du1aa9i.png",
   },
   "clash": {
      "name": "Clash",
      "safename": "clash",
      "realname": "Morowa Evans",
      "birthplace": "London, England",
      "age": 35,
      "date_of_birth": "June 7th",
      "season_introduced": "Y3S3",
      "health": 3,
      "speed": 1,
      "unit": "MPS",
      "country_code": "GB",
      "roles": ["Crowd Control", "Intel Gatherer", "Secure", "Shield"],
      "side": "defender",
      "icon_url": "https://i.imgur.com/eogGdHx.png",
   },
   "maverick": {
      "name": "Maverick",
      "safename": "maverick",
      "realname": "Erik Thorn",
      "birthplace": "Boston, Massachusetts",
      "age": 36,
      "date_of_birth": "April 20th",
      "season_introduced": "Y3S3",
      "health": 1,
      "speed": 3,
      "unit": "THE UNIT",
      "country_code": "US",
      "roles": ["Back Line", "Disable", "Flank", "Hard Breach"],
      "side": "attacker",
      "icon_url": "https://i.imgur.com/8hXt5z6.png",
   },
   "maestro": {
      "name": "Maestro",
      "safename": "maestro",
      "realname": "Adriano Martello",
      "birthplace": "Rome, Italy",
      "age": 45,
      "date_of_birth": "April 13th",
      "season_introduced": "Y3S2",
      "health": 3,
      "speed": 1,
      "unit": "G.I.S.",
      "country_code": "IT",
      "roles": ["Anchor", "Area Denial", "Intel Gatherer", "Secure"],
      "side": "defender",
      "icon_url": "https://i.imgur.com/PQ8VBAF.png",
   },
   "alibi": {
      "name": "Alibi",
      "safename": "alibi",
      "realname": "Aria de Luca",
      "birthplace": "Tripoli, Libya",
      "age": 37,
      "date_of_birth": "December 15th",
      "season_introduced": "Y3S2",
      "health": 1,
      "speed": 3,
      "unit": "G.I.S.",
      "country_code": "IT",
      "roles": ["Intel Denier", "Intel Gatherer", "Roam", "Trap"],
      "side": "defender",
      "icon_url": "https://i.imgur.com/Phb6OUU.png",
   },
   "lion": {
      "name": "Lion",
      "safename": "lion",
      "realname": "Olivier Flament",
      "birthplace": "Toulouse, France",
      "age": 31,
      "date_of_birth": "August 29th",
      "season_introduced": "Y3S1",
      "health": 2,
      "speed": 2,
      "unit": "GIGN",
      "country_code": "FR",
      "roles": ["Anti Roam", "Back Line", "Crowd Control", "Intel Gatherer"],
      "side": "attacker",
      "icon_url": "https://i.imgur.com/0zCtOUO.png",
   },
   "finka": {
      "name": "Finka",
      "safename": "finka",
      "realname": "Lera Melnikova",
      "birthplace": "Gomel, Belarus",
      "age": 32,
      "date_of_birth": "June 7",
      "season_introduced": "Y3S1",
      "health": 2,
      "speed": 2,
      "unit": "SPETSNAZ",
      "country_code": "RU",
      "roles": ["Back Line", "Buff"],
      "side": "attacker",
      "icon_url": "https://i.imgur.com/dxqOJu3.png",
   },
   "vigil": {
      "name": "Vigil",
      "safename": "vigil",
      "realname": "Chul Kyung Hwa",
      "birthplace": "REDACTED",
      "age": 34,
      "date_of_birth": "January 17th",
      "season_introduced": "Y2S4",
      "health": 1,
      "speed": 3,
      "unit": "707TH SMB",
      "country_code": "SK",
      "roles": ["Intel Denier", "Roam"],
      "side": "defender",
      "icon_url": "https://i.imgur.com/WkqMEZ6.png",
   },
   "dokkaebi": {
      "name": "Dokkaebi",
      "safename": "dokkaebi",
      "realname": "Grace Nam",
      "birthplace": "Seoul, South Korea",
      "age": 29,
      "date_of_birth": "February 2nd",
      "season_introduced": "Y2S4",
      "health": 1,
      "speed": 3,
      "unit": "707TH SMB",
      "country_code": "SK",
      "roles": ["Anti Roam", "Flank", "Intel Denier", "Intel Gatherer"],
      "side": "attacker",
      "icon_url": "https://i.imgur.com/iVLOHr2.png",
   },
   "zofia": {
      "name": "Zofia",
      "safename": "zofia",
      "realname": "Zofia Bosak",
      "birthplace": "Wrocław, Poland",
      "age": 36,
      "date_of_birth": "January 28th",
      "season_introduced": "Y2S4",
      "health": 3,
      "speed": 1,
      "unit": "G.R.O.",
      "country_code": "PL",
      "roles": ["Anti Roam", "Crowd Control", "Disable", "Flank", "Soft Breach"],
      "side": "attacker",
      "icon_url": "https://i.imgur.com/AMOYwMJ.png",
   },
   "ela": {
      "name": "Ela",
      "safename": "ela",
      "realname": "Elżbieta Bosak",
      "birthplace": "Wrocław, Poland",
      "age": 31,
      "date_of_birth": "November 8th",
      "season_introduced": "Y2S4",
      "health": 2,
      "speed": 2,
      "unit": "G.R.O.",
      "country_code": "PL",
      "roles": ["Crowd Control", "Roam", "Trap"],
      "side": "defender",
      "icon_url": "https://i.imgur.com/OwjSJNB.png",
   },
   "ying": {
      "name": "Ying",
      "safename": "ying",
      "realname": "Siu Mei Lin",
      "birthplace": "Hong Kong, Central",
      "age": 33,
      "date_of_birth": "May 12th",
      "season_introduced": "Y2S3",
      "health": 2,
      "speed": 2,
      "unit": "S.D.U",
      "country_code": "HK",
      "roles": ["Crowd Control", "Front Line"],
      "side": "attacker",
      "icon_url": "https://i.imgur.com/BHUvTt4.png",
   },
   "lesion": {
      "name": "Lesion",
      "safename": "lesion",
      "realname": "Liu Tze Long",
      "birthplace": "Hong Kong, Junk Bay (Tseung Kwan O)",
      "age": 44,
      "date_of_birth": "July 2nd",
      "season_introduced": "Y2S3",
      "health": 2,
      "speed": 2,
      "unit": "S.D.U",
      "country_code": "HK",
      "roles": ["Anchor", "Crowd Control", "Intel Gatherer", "Roam", "Trap"],
      "side": "defender",
      "icon_url": "https://i.imgur.com/IvYOwrI.png",
   },
   "mira": {
      "name": "Mira",
      "safename": "mira",
      "realname": "Elena María Álvarez",
      "birthplace": "Madrid, Spain",
      "age": 39,
      "date_of_birth": "November 18th",
      "season_introduced": "Y2S1",
      "health": 3,
      "speed": 1,
      "unit": "G.E.O.",
      "country_code": "ES",
      "roles": ["Anchor", "Intel Gatherer", "Secure"],
      "side": "defender",
      "icon_url": "https://i.imgur.com/gOnJqiF.png",
   },
   "jackal": {
      "name": "Jackal",
      "safename": "jackal",
      "realname": "Ryad Ramírez Al-Hassar",
      "birthplace": "Ceuta, Spain",
      "age": 49,
      "date_of_birth": "February 29th",
      "season_introduced": "Y2S1",
      "health": 2,
      "speed": 2,
      "unit": "G.E.O.",
      "country_code": "ES",
      "roles": ["Anti Roam", "Intel Gatherer"],
      "side": "attacker",
      "icon_url": "https://i.imgur.com/cGBKp2a.png",
   },
   "hibana": {
      "name": "Hibana",
      "safename": "hibana",
      "realname": "Yumiko Imagawa",
      "birthplace": "Nagoya, Japan",
      "age": 34,
      "date_of_birth": "July 12th",
      "season_introduced": "Y1S4",
      "health": 1,
      "speed": 3,
      "unit": "S.A.T.",
      "country_code": "JP",
      "roles": ["Back Line", "Front Line", "Hard Breach"],
      "side": "attacker",
      "icon_url": "https://i.imgur.com/aqOOm2R.png",
   },
   "echo": {
      "name": "Echo",
      "safename": "echo",
      "realname": "Masaru Enatsu",
      "birthplace": "Tokyo, Japan (Suginami-ku)",
      "age": 36,
      "date_of_birth": "October 31st",
      "season_introduced": "Y1S4",
      "health": 2,
      "speed": 2,
      "unit": "S.A.T.",
      "country_code": "JP",
      "roles": ["Anchor", "Crowd Control", "Intel Gatherer", "Secure"],
      "side": "defender",
      "icon_url": "https://i.imgur.com/OMNe9qB.png",
   },
   "caveira": {
      "name": "Caveira",
      "safename": "caveira",
      "realname": "Taina Pereira",
      "birthplace": "Rinópolis, Brazil",
      "age": 27,
      "date_of_birth": "October 15th",
      "season_introduced": "Y1S3",
      "health": 1,
      "speed": 3,
      "unit": "BOPE",
      "country_code": "BR",
      "roles": ["Intel Denier", "Intel Gatherer", "Roam"],
      "side": "defender",
      "icon_url": "https://i.imgur.com/IeYRobc.png",
   },
   "capitao": {
      "name": "Capitão",
      "safename": "capitao",
      "realname": "Vicente Souza",
      "birthplace": "Rio de Janeiro, Brazil (Nova Iguaçu)",
      "age": 49,
      "date_of_birth": "November 17th",
      "season_introduced": "Y1S3",
      "health": 1,
      "speed": 3,
      "unit": "BOPE",
      "country_code": "BR",
      "roles": ["Area Denial", "Flank", "Front Line"],
      "side": "attacker",
      "icon_url": "https://i.imgur.com/gBmMrMa.png",
   },
   "blackbeard": {
      "name": "Blackbeard",
      "safename": "blackbeard",
      "realname": "Craig Jenson",
      "birthplace": "Bellevue, Washington",
      "age": 32,
      "date_of_birth": "March 12th",
      "season_introduced": "Y1S2",
      "health": 2,
      "speed": 2,
      "unit": "NAVY SEAL",
      "country_code": "US",
      "roles": ["Back Line", "Covering Fire", "Shield"],
      "side": "attacker",
      "icon_url": "https://i.imgur.com/BOAh5x8.png",
   },
   "valkyrie": {
      "name": "Valkyrie",
      "safename": "valkyrie",
      "realname": "Meghan J. Castellano",
      "birthplace": "Oceanside, California",
      "age": 31,
      "date_of_birth": "July 21st",
      "season_introduced": "Y1S2",
      "health": 2,
      "speed": 2,
      "unit": "NAVY SEAL",
      "country_code": "US",
      "roles": ["Intel Gatherer", "Roam"],
      "side": "defender",
      "icon_url": "https://i.imgur.com/xJHdqA3.png",
   },
   "buck": {
      "name": "Buck",
      "safename": "buck",
      "realname": "Sebastien Côté",
      "birthplace": "Montreal, QC",
      "age": 36,
      "date_of_birth": "August 20th",
      "season_introduced": "Y1S1",
      "health": 2,
      "speed": 2,
      "unit": "JTF2",
      "country_code": "CA",
      "roles": ["Flank", "Soft Breach"],
      "side": "attacker",
      "icon_url": "https://i.imgur.com/u9slUlM.png",
   },
   "frost": {
      "name": "Frost",
      "safename": "frost",
      "realname": "Tina Lin Tsang",
      "birthplace": "Vancouver, British Columbia",
      "age": 32,
      "date_of_birth": "May 4th",
      "season_introduced": "Y1S1",
      "health": 2,
      "speed": 2,
      "unit": "JTF2",
      "country_code": "CA",
      "roles": ["Crowd Control", "Trap"],
      "side": "defender",
      "icon_url": "https://i.imgur.com/FTbAE33.png",
   },
   "mute": {
      "name": "Mute",
      "safename": "mute",
      "realname": "Mark R. Chandar",
      "birthplace": "York, England",
      "age": 25,
      "date_of_birth": "October 11th",
      "season_introduced": "Y0S0",
      "health": 3,
      "speed": 1,
      "unit": "SAS",
      "country_code": "GB",
      "roles": ["Anti Hard Breach", "Intel Denier", "Secure"],
      "side": "defender",
      "icon_url": "https://i.imgur.com/peaKoO1.png",
   },
   "sledge": {
      "name": "Sledge",
      "safename": "sledge",
      "realname": "Seamus Cowden",
      "birthplace": "John O’Groats, Scotland",
      "age": 35,
      "date_of_birth": "April 2nd",
      "season_introduced": "Y0S0",
      "health": 3,
      "speed": 1,
      "unit": "SAS",
      "country_code": "GB",
      "roles": ["Flank", "Soft Breach"],
      "side": "attacker",
      "icon_url": "https://i.imgur.com/JXV80ZY.png",
   },
   "smoke": {
      "name": "Smoke",
      "safename": "smoke",
      "realname": "James Porter",
      "birthplace": "London, England (King's Cross)",
      "age": 36,
      "date_of_birth": "May 14th",
      "season_introduced": "Y0S0",
      "health": 2,
      "speed": 2,
      "unit": "SAS",
      "country_code": "GB",
      "roles": ["Anchor", "Area Denial", "Secure"],
      "side": "defender",
      "icon_url": "https://i.imgur.com/aodW3TF.png",
   },
   "thatcher": {
      "name": "Thatcher",
      "safename": "thatcher",
      "realname": "Mike Baker",
      "birthplace": "Bideford, England",
      "age": 56,
      "date_of_birth": "June 22nd",
      "season_introduced": "Y0S0",
      "health": 3,
      "speed": 1,
      "unit": "SAS",
      "country_code": "GB",
      "roles": ["Back Line", "Disable"],
      "side": "attacker",
      "icon_url": "https://i.imgur.com/BuEp8mz.png",
   },
   "ash": {
      "name": "Ash",
      "safename": "ash",
      "realname": "Eliza Cohen",
      "birthplace": "Jerusalem, Israel",
      "age": 33,
      "date_of_birth": "December 24th",
      "season_introduced": "Y0S0",
      "health": 1,
      "speed": 3,
      "unit": "SWAT",
      "country_code": "US",
      "roles": ["Disable", "Flank", "Front Line", "Soft Breach"],
      "side": "attacker",
      "icon_url": "https://i.imgur.com/ml0tMs3.png",
   },
   "castle": {
      "name": "Castle",
      "safename": "castle",
      "realname": "Miles Campbell",
      "birthplace": "Sherman Oaks, California",
      "age": 36,
      "date_of_birth": "September 20th",
      "season_introduced": "Y0S0",
      "health": 2,
      "speed": 2,
      "unit": "SWAT",
      "country_code": "US",
      "roles": ["Anchor", "Secure"],
      "side": "defender",
      "icon_url": "https://i.imgur.com/Fv8G4RW.png",
   },
   "pulse": {
      "name": "Pulse",
      "safename": "pulse",
      "realname": "Jack Estrada",
      "birthplace": "Goldsboro, North Carolina",
      "age": 32,
      "date_of_birth": "October 11th",
      "season_introduced": "Y0S0",
      "health": 1,
      "speed": 3,
      "unit": "SWAT",
      "country_code": "US",
      "roles": ["Intel Gatherer", "Roam"],
      "side": "defender",
      "icon_url": "https://i.imgur.com/Y2iDnWq.png",
   },
   "thermite": {
      "name": "Thermite",
      "safename": "thermite",
      "realname": "Jordan Trace",
      "birthplace": "Plano, Texas",
      "age": 35,
      "date_of_birth": "March 14th",
      "season_introduced": "Y0S0",
      "health": 2,
      "speed": 2,
      "unit": "SWAT",
      "country_code": "US",
      "roles": ["Back Line", "Hard Breach"],
      "side": "attacker",
      "icon_url": "https://i.imgur.com/o896oL9.png",
   },
   "montagne": {
      "name": "Montagne",
      "safename": "montagne",
      "realname": "Gilles Touré",
      "birthplace": "Bordeaux, France",
      "age": 48,
      "date_of_birth": "October 11th",
      "season_introduced": "Y0S0",
      "health": 3,
      "speed": 1,
      "unit": "GIGN",
      "country_code": "FR",
      "roles": ["Shield"],
      "side": "attacker",
      "icon_url": "https://i.imgur.com/bzzVRTU.png",
   },
   "twitch": {
      "name": "Twitch",
      "safename": "twitch",
      "realname": "Emmanuelle Pichon",
      "birthplace": "ancy, France",
      "age": 28,
      "date_of_birth": "October 12th",
      "season_introduced": "Y0S0",
      "health": 2,
      "speed": 2,
      "unit": "GIGN",
      "country_code": "FR",
      "roles": ["Back Line", "Disable", "Front Line", "Intel Gatherer"],
      "side": "attacker",
      "icon_url": "https://i.imgur.com/jc5pPPK.png",
   },
   "doc": {
      "name": "Doc",
      "safename": "doc",
      "realname": "Gustave Kateb",
      "birthplace": "aris, France",
      "age": 39,
      "date_of_birth": "September 16th",
      "season_introduced": "Y0S0",
      "health": 3,
      "speed": 1,
      "unit": "GIGN",
      "country_code": "FR",
      "roles": ["Anchor", "Buff"],
      "side": "defender",
      "icon_url": "https://i.imgur.com/19gitiC.png",
   },
   "rook": {
      "name": "Rook",
      "safename": "rook",
      "realname": "Julien Nizan",
      "birthplace": "Tours, France",
      "age": 27,
      "date_of_birth": "January 6th",
      "season_introduced": "Y0S0",
      "health": 3,
      "speed": 1,
      "unit": "GIGN",
      "country_code": "FR",
      "roles": ["Anchor", "Buff"],
      "side": "defender",
      "icon_url": "https://i.imgur.com/UQK1UNc.png",
   },
   "jager": {
      "name": "Jäger",
      "safename": "jager",
      "realname": "Marius Streicher",
      "birthplace": "Düsseldorf, Germany",
      "age": 39,
      "date_of_birth": "March 9th",
      "season_introduced": "Y0S0",
      "health": 2,
      "speed": 2,
      "unit": "GSG9",
      "country_code": "DE",
      "roles": ["Roam", "Secure"],
      "side": "defender",
      "icon_url": "https://i.imgur.com/Y8EjdSy.png",
   },
   "bandit": {
      "name": "Bandit",
      "safename": "bandit",
      "realname": "Dominic Brunsmeier",
      "birthplace": "Berlin, Germany",
      "age": 42,
      "date_of_birth": "August 13th",
      "season_introduced": "Y0S0",
      "health": 1,
      "speed": 3,
      "unit": "GSG9",
      "country_code": "DE",
      "roles": ["Anti Hard Breach", "Roam", "Secure"],
      "side": "defender",
      "icon_url": "https://i.imgur.com/p6tWAW7.png",
   },
   "blitz": {
      "name": "Blitz",
      "safename": "blitz",
      "realname": "Elias Kötz",
      "birthplace": "Bremen, Germany",
      "age": 37,
      "date_of_birth": "April 2nd",
      "season_introduced": "Y0S0",
      "health": 2,
      "speed": 2,
      "unit": "GSG9",
      "country_code": "DE",
      "roles": ["Anti Roam", "Crowd Control", "Front Line", "Shield"],
      "side": "attacker",
      "icon_url": "https://i.imgur.com/GxXncfV.png",
   },
   "iq": {
      "name": "IQ",
      "safename": "iq",
      "realname": "Monika Weiss",
      "birthplace": "Leipzig, Germany",
      "age": 38,
      "date_of_birth": "August 1st",
      "season_introduced": "Y0S0",
      "health": 1,
      "speed": 3,
      "unit": "GSG9",
      "country_code": "DE",
      "roles": ["Disable", "Flank", "Front Line", "Intel Gatherer"],
      "side": "attacker",
      "icon_url": "https://i.imgur.com/M1NaKKv.png",
   },
   "fuze": {
      "name": "Fuze",
      "safename": "fuze",
      "realname": "Shuhrat Kessikbayev",
      "birthplace": "Samarkand, Uzbekistan",
      "age": 39,
      "date_of_birth": "October 12th",
      "season_introduced": "Y0S0",
      "health": 3,
      "speed": 1,
      "unit": "SPETSNAZ",
      "country_code": "RU",
      "roles": ["Area Denial", "Disable", "Flank"],
      "side": "attacker",
      "icon_url": "https://i.imgur.com/xsVA73Z.png",
   },
   "glaz": {
      "name": "Glaz",
      "safename": "glaz",
      "realname": "Timur Glazkov",
      "birthplace": "Vladivostok, Primorsky Krai, Russia",
      "age": 34,
      "date_of_birth": "July 2nd",
      "season_introduced": "Y0S0",
      "health": 1,
      "speed": 3,
      "unit": "SPETSNAZ",
      "country_code": "RU",
      "roles": ["Back Line", "Covering Fire", "Soft Breach"],
      "side": "attacker",
      "icon_url": "https://i.imgur.com/7vFvnxZ.png",
   },
   "tachanka": {
      "name": "Tachanka",
      "safename": "tachanka",
      "realname": "Alexsandr Senaviev",
      "birthplace": "Saint Petersburg, Russia",
      "age": 54,
      "date_of_birth": "November 3rd",
      "season_introduced": "Y0S0",
      "health": 3,
      "speed": 1,
      "unit": "SPETSNAZ",
      "country_code": "RU",
      "roles": ["Anchor", "Covering Fire", "Shield"],
      "side": "defender",
      "icon_url": "https://i.imgur.com/VTUCIZH.png",
   },
   "kapkan": {
      "name": "Kapkan",
      "safename": "kapkan",
      "realname": "Maxim Basuda",
      "birthplace": "Kovrov, Vladimir Oblast, Russia",
      "age": 42,
      "date_of_birth": "May 14th",
      "season_introduced": "Y0S0",
      "health": 2,
      "speed": 2,
      "unit": "SPETSNAZ",
      "country_code": "RU",
      "roles": ["Trap"],
      "side": "defender",
      "icon_url": "https://i.imgur.com/YHj9igl.png",
   },

   # Don't know any of this, but might as well be
   "no class": {
      "name": "Recruit",
      "safename": "recruit",
      "realname": "Unknown",
      "birthplace": "Unknown",
      "age": 00,
      "date_of_birth": "Unknown",
      "season_introduced": "Y0S0",
      "health": 1,
      "speed": 1,
      "unit": "UNAFFILIATED",
      "country_code": "",
      "roles": [],
      "side": "defender",
      "icon_url": "https://i.imgur.com/PSVGuqT.png"
   }
}
